### PR TITLE
OSX Docker support

### PR DESCRIPTION
**Pull request by beatscode**
I've been having difficulty getting my local installation of hh_client to work right. [Open Issue](https://github.com/hhvm/homebrew-hhvm/issues/86) .  However, my working hack project is operational in docker.  This PR will allow users to tap into a docker container's version of Hack tools without having to build hhvm locally.  Also whenever new features to hh_client/hackificator are introduced one could more easily test/play with them without having to build hhvm each time.
Please feel free to suggest any changes that suit your style most.

### CODE REVIEW

**Comment by PranayAgarwal** [comment]
This works for me, but I think @fredemmott was able to get hh_client on Docker working without any code changes?

**Comment by PranayAgarwal** [comment]
Could you also fix some of the obvious linting errors?

**Comment by fredemmott** [comment]
https://github.com/fredemmott/nuclide-customization is how I did this.

**Comment by beatscode** [comment]
Thanks 👍

**Pull request merged**
